/**
 * Secret bindings.
 *
 * `worker-configuration.d.ts` is generated by `wrangler types` from
 * wrangler.jsonc, so it only knows about `vars` — secrets set via
 * `wrangler secret put` are absent and get wiped from that file on every
 * regeneration. Declaring them here keeps them typed and safe from that.
 *
 * All are optional: the code must handle an unset secret deliberately (the API
 * guard fails closed, Turnstile falls back to the test key, Telegram logging
 * stays off) rather than assuming configuration is complete.
 *
 * Set for production with:
 *   bunx wrangler secret put API_KEY
 *   bunx wrangler secret put SESSION_SECRET
 *   bunx wrangler secret put TURNSTILE_SECRET_KEY
 * For local dev put them in .dev.vars (gitignored).
 */
declare namespace Cloudflare {
	interface Env {
		/** Shared key for machine API clients. */
		API_KEY?: string;
		/** HMAC signing key for dashboard session cookies. */
		SESSION_SECRET?: string;
		/** Turnstile secret, paired with the public TURNSTILE_SITE_KEY var. */
		TURNSTILE_SECRET_KEY?: string;
		/** Telegram logging (optional, gated by TELEGRAM_LOG_ENABLE). */
		TELEGRAM_BOT_TOKEN?: string;
		TELEGRAM_CHAT_ID?: string;
	}
}

/**
 * `wrangler types` emits each var's *literal* value as its type, so
 * TURNSTILE_SITE_KEY is typed `""` while the placeholder is empty — which makes
 * the compiler treat a configured key as impossible. Widen it to string via
 * interface merging so the fallback in dashboardRoutes stays type-correct
 * whether or not a key is set.
 */
interface CloudflareBindings {
	TURNSTILE_SITE_KEY: string;
}
